AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda to respond to Twilio requests
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Runtime: python3.7

Resources:
  TriggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.main
      Timeout: 10
      MemorySize: 128
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: '/'
            Method: get
      ReservedConcurrentExecutions: 1
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 'ssm:GetParameter*'
              Resource:
                - !Sub "arn:aws:ssm:*:${AWS::AccountId}:parameter/twilio/*"
                - !Sub "arn:aws:ssm:*:${AWS::AccountId}:parameter/wmata/*"

